name: Deploy to eceusc.ucsd.edu

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: npm install 
    - run: npm run build
    - run: ls -lah  
    - uses: os-ucsd/actions/acsweb@0.1.0
      with:
        username: eceusc
        password: "${{secrets.ACSWEB_PASSWORD}}"
        local_dir: "./build/"